main: tk.shanebee.eventSupport.EventSupport
name: EventHandler
version: '${project.version}'
api-version: '1.13'
author: ShaneBee
website: https://github.com/ShaneBeee/EventHandler
description: Allowing server admins to cancel certain events

commands:
  eventhandler:
    description: <reload> and <about>
    permission: eventhandler.admin
    aliases: eh
    usage: /eventhandler <about/enable/disable/list/reload>

permissions:
  eventhandler.admin:
    description: Allows admins to reload config and use list command as well as enable/disable events via command
    default: op
  eventhandler.bypass.*:
    description: Bypasses all cancelled events
    default: op
    children:
      eventhandler.bypass.breed: true
      eventhandler.bypass.bucketfill: true
      eventhandler.bypass.bucketempty: true
      eventhandler.bypass.consumepotion: true
      eventhandler.bypass.consumemilk: true
      eventhandler.bypass.creativeinvdrop: true
      eventhandler.bypass.dropitem: true
      eventhandler.bypass.enterbedevent: true
      eventhandler.bypass.fishing: true
      eventhandler.bypass.jump: true
      eventhandler.bypass.tabcomplete: true
      eventhandler.bypass.tame: true
      eventhandler.bypass.throwneggspawnchicken: true
      eventhandler.bypass.throwegg: true
      eventhandler.bypass.throwsnowball: true
      eventhandler.bypass.togglesprint: true
      eventhandler.bypass.tramplecrops: true
      eventhandler.bypass.trampleeggs: true

  eventhandler.bypass.breed:
    description: Bypasses the breed event
    default: op
  eventhandler.bypass.bucketfill:
    description: Bypasses the bucket fill event
    default: op
  eventhandler.bypass.bucketempty:
    description: Bypasses the bucket empty event
    default: op
  eventhandler.bypass.consumepotion:
    description: Bypasses the consume potion event
    default: op
  eventhandler.bypass.consumemilk:
    description: Bypasses the consume milk event
    default: op
  eventhandler.bypass.creativeinvdrop:
    description: Bypasses the creative inv drop event
    default: op
  eventhandler.bypass.dropitem:
    description: Bypasses the item drop event
    default: op
  eventhandler.bypass.enterbedevent:
    description: Bypasses the enter bed event
    default: op
  eventhandler.bypass.fishing:
    description: Bypasses the fishing event
    default: op
  eventhandler.bypass.jump:
    description: Bypasses the jump event
    default: op
  eventhandler.bypass.tabcomplete:
    description: Bypasses the tab complete event
    default: op
  eventhandler.bypass.tame:
    description: Bypasses the tame event
    default: op
  eventhandler.bypass.throwneggspawnchicken:
    description: Bypasses the thrown egg spawn chicken event
    default: op
  eventhandler.bypass.throwegg:
    description: Bypasses the throwing egg event
    default: op
  eventhandler.bypass.throwsnowball:
    description: Bypasses the throwing snowball event
    default: op
  eventhandler.bypass.togglesprint:
    description: Bypasses the toggle sprint event
    default: op
  eventhandler.bypass.tramplecrops:
    description: Bypasses the crop trample event
    default: op
  eventhandler.bypass.trampleeggs:
    description: Bypasses the egg trample event
    default: op
